<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="L33986WUS" name="com.webdriver.questions.TestWebdriverWaitClass" tests="1" failures="0" timestamp="16 May 2020 21:25:34 GMT" time="6.904" errors="1">
  <testcase name="test_ignoring_of_exception_in_waitclass" time="6.904" classname="com.webdriver.questions.TestWebdriverWaitClass">
    <error type="java.util.NoSuchElementException" message="Intentionally Done">
      <![CDATA[java.util.NoSuchElementException: Intentionally Doneat com.webdriver.questions.TestWebdriverWaitClass$1.apply(TestWebdriverWaitClass.java:36)at com.webdriver.questions.TestWebdriverWaitClass$1.apply(TestWebdriverWaitClass.java:1)at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)at com.webdriver.questions.TestWebdriverWaitClass.test_ignoring_of_exception_in_waitclass(TestWebdriverWaitClass.java:49)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- test_ignoring_of_exception_in_waitclass -->
</testsuite> <!-- com.webdriver.questions.TestWebdriverWaitClass -->
